### ISSUE TITLE
Error : invalid number of images in '.\capture_0'

### ISSUE THREAD

**Issue by YeShangguan** [kamino410/procam-calibration#1]
When I'm trying to calibrate the images under the sample_data/capture_0, an error occurred. I noticed that the value of len(gc_filenames) is 42 and the value of graycode.getNumberOfPatternImages() is 42.This means that len(gc_filenames) != graycode.getNumberOfPatternImages() + 2.I just don't know why this error occurred and what's the exact meaning of graycode.getNumberOfPatternImages() .

**Comment by YeShangguan** [comment]
I've tried to add the copy of last 2 images in the path \ capture_0,then the program ran successfully.But the RMS error was very big.

**Comment by kamino410** [comment]
Sorry for being late...

I guess that you ran the caliblate.py with graycode_step=1.
But the sample_data was captured with graycode_step=2.
I added a sample command to README.
