### ISSUE TITLE
How should we assess quality of results?

### ISSUE THREAD

**Issue by eldrickm** [kamino410/procam-calibration#10]
Hello,

1. How should we interpret RMS? 
2. What are typical values for RMS to expect?

Thank you!

**Comment by eldrickm** [comment]
I currently get on the values order of 1.0-5.0 for RMS with about 5-10 captures

**Comment by eldrickm** [comment]
1. RMS is RMS of reproduction error in pixels
2. Acceptable values should be < 1.0, with good being < 0.5

A good resource on calibration guidelines:
https://pgaleone.eu/computer-vision/2018/03/04/camera-calibration-guidelines/

They advocate for ~50 images for a calibration.

@kamino410 In practice how many images do you recommend for this method / implementation?

**Comment by kamino410** [comment]
@eldrickm 
About the RMS and # of captures, I cannot say for sure. They depend on # of corners, size of checker board, FoV / resolutions of your projector and camera, relative pose between your projector and camera, strength of lens distortion and accuracy of device assembly.
Please capture images as possible with different board poses.
