### ISSUE TITLE
AttributeError: 'cv2.structured_light_GrayCodePattern' object has no attribute 'generate'

### ISSUE THREAD

**Issue by dawid-szewc** [kamino410/procam-calibration#12]
AttributeError: 'cv2.structured_light_GrayCodePattern' object has no attribute 'generate'
How to fix it?

**Comment by kamino410** [comment]
@Xephen20 
Unfortunately, the opencv-python and opencv-contrib-python packages on pip are sometimes released in a broken state.
Try to roll back your packages (for example 4.5.0 or 4.4.x).

**Comment by dawid-szewc** [comment]
Okey, thanks for fast response ;)
