### ISSUE TITLE
How can I use the finnal  calibration_result.xml?

### ISSUE THREAD

**Issue by timeanddoctor** [kamino410/procam-calibration#6]
Thank you very much for this great works.
I am a really newbility one for the visual study . I can calibrate my camera and projector by this projection.
What I am doing is to map some points to a 3d printing model.  Can I project the texture to the model?

**Comment by kamino410** [comment]
Hi.

The `calibration_result.xml` is just a xml file which contains the calibrated parameters and is readable by the OpenCV's `filestorage` class.
I have not intend to read this file from a specific software.

----

Applications of the projector-camera system are off the topic of this repository.
So, I would like to provide only some hints.

The basic procedure of dynamic projection mapping is as follows.
1. Design a CG scene that mimics the real scene.
    * It consists with the target objects and projector.
    * In the CG scene, the real projector is defined as a camera whose parameters (FoV, optical axis, and pose) equal to the real projector's one.
    * The calibrated parameters of the projector are used here.
    * [These scripts](https://github.com/kamino410/cv-snippets/tree/master/unity) might be helpful.
2. [Real time] Capture the markers on the target objects from the real camera, and estimate their poses (positions and rotations) by solving perspective n-points (PnP) problem.
    * There are several types of markers and methods of pose estimation.
    * The calibrated parameters of the camera are used here.
3. [Real time] Update the poses of the target objects in the CG scene.
4. [Real time] Render a image from the view point of the camera in CG scene (=pseudo projector).
5. [Real time] Project the rendered image from the real projector.

If you want to project to static objects, you can skip the process 2 & 3 by adjusting the poses of target objects manually.

Most of the above process can be implemented by using Unity (or OpenGL) and OpenCV.
But, it might be hard to implemente a high-quality tracking by a single camera.

Good luck.
