### ISSUE TITLE
Could you tell me the version of opencv

### ISSUE THREAD

**Issue by Colbert-Ran** [kamino410/procam-calibration#9]
I try to run your code, but got some problem. The version of 4.5 is not compatible. Could you tell me the version of opencv? Thanks.

**Comment by kamino410** [comment]
@ColbertBrave
This project depends on stable modules of OpenCV, so any version should work correctly.
Unfortunately, however, the opencv-python and opencv-contrib-python packages on pip are sometimes released in a broken state.
Try to roll back your packages (for example 4.5.0 or 4.4.x).

**Comment by kamino410** [comment]
@ColbertBrave Can I close this issue?

**Comment by Colbert-Ran** [comment]
Yes. Thank you very much. I try the 4.4.0 and it works well.
